theme = "my-onelight"

[editor]
line-number = "relative"
completion-trigger-len = 1
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
idle-timeout = 0
bufferline = "always"
color-modes = true

[editor.indent-guides]
render = true
character = "¦"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
tab = "indent"
S-tab = "unindent"

[keys.normal.space]
z = ":quit"
