theme = "my-onelight"

[editor]
line-number = "relative"
completion-trigger-len = 1
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
idle-timeout = 100
bufferline = "always"
color-modes = true

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "¦"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal.'\']
# https://github.com/helix-editor/helix/issues/2806#issuecomment-1551801413
space = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']
'\' = [''':sh tmux send-keys Q/# Space %% Enter O# Escape Escape Nvg.a BSpace BSpace Escape Escape \\ Space uuQ''']
# the above is the quivalent of putting, in .tmux.conf: send-keys Q/#\s%%\rO#\e\eNvg.a\b\b\e\e\\\suuQ

[keys.normal]
C-i = "jump_forward"
C-o = "jump_backward"
# TODO This interferres with `jump_forward` for some stupid reason
# tab = "indent"
# S-tab = "unindent"

[keys.normal.space]
z = ":quit"
