theme = "my-onelight"

[editor]
line-number = "relative"
completion-trigger-len = 1
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
idle-timeout = 0
bufferline = "always"
color-modes = true

[editor.indent-guides]
render = true
character = "⋮"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
