function powerline_precmd() {
    PS1="$(powerline-go -error $? -shell zsh)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi


# Use fzf
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

# Define alias for nix-shell that drops you into zsh
alias nix-zsh="nix-shell --run zsh"

# Setup direnv
eval "$(direnv hook zsh)"

# Zsh hist config
HISTSIZE=100000
# Ignore dupblicates when saving the history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
# Do not record commands that start with one space
setopt HIST_IGNORE_SPACE
