cursor #1c1b1d
cursor_text_color #49454c

foreground            #1c1b1d
background            #fdf8fa
selection_foreground  #ffffff
selection_background  #cbc4d2
url_color             #4a425b

color0   #141315
color1   #79303f
color2   #215f2e
color3   #997b26
color4   #4c435f
color5   #9792a1
color6   #4a425b
color7   #222223
color8   #6a696c
color9   #a65866
color10  #3f8c4f
color11  #a58731
color12  #756a8b
color13  #9792a1
color14  #6b6676
color15  #bcbbbf
