cursor #1b1b1b
cursor_text_color #474747

foreground            #1b1b1b
background            #f9f9f9
selection_foreground  #ffffff
selection_background  #dec2a2
url_color             #845400

color0   #131313
color1   #8c0b39
color2   #307209
color3   #7f4d11
color4   #ffbf4c
color5   #704b0b
color6   #845400
color7   #1a1a1a
color8   #2e2e2e
color9   #a5204f
color10  #408c13
color11  #996221
color12  #9e6400
color13  #ff973f
color14  #ebff59
color15  #1a1a1a
