[colors]
background=fafafa
foreground=383a42

# regular
regular0=383a42  # black
regular1=e45649  # red
regular2=50a14f  # green
regular3=c18401  # yellow
regular4=0184bc  # blue
regular5=a626a4  # magenta
regular6=0997b3  # cyan
regular7=fafafa  # white (light background)

# bright
bright0=4f525d
bright1=df6c75
bright2=98c379
bright3=e5c07b
bright4=61afef
bright5=c678dd
bright6=56b6c2
bright7=ffffff

# optional (but recommended)
selection-background=e5e5e6
selection-foreground=383a42

[main]
font=Iosevka Nerd Font:size=12

[csd]
size=0
